### ISSUE TITLE
Is there a sample project or other usage documentation available

### ISSUE THREAD

**Issue by ydsood** [dotnet/xdt#435]
Not sure if this is the correct location to ask usage related questions but I did not find any other location to do that. I am trying to run a web.config transformation using commands in the .csproj file of my project.

**Project Details**
AspNetCore 2.1.x project targeting .Net Framework 4.6.1.

**Use Case**
I want to change the value of an attribute in the generated web.config file for my project. I use `dotnet publish` to publish the project for IIS deployment and I want directives in the csproj to trigger transformation of the generated web.config file. I am trying to add a nuget reference to project and leverage it for the transformation in a way similar to (1) https://github.com/nil4/dotnet-transform-xdt#-project-level-dotnet-transform-xdt-tool- or (2) https://stackoverflow.com/a/10506476/4764075

Can this library be leveraged to this end. If so, are there any examples available for that. If not, since this has been quoted as the library responsible for transforming web.config by Visual Studio and .NET CLI, would you recommend some other ways to approach solving this problem?

**Comment by ydsood** [comment]
I was able to find the examples here https://github.com/vijayrkn/webconfigtransform
Specifically this
`dotnet publish /p:Configuration=Release /p:CustomTransformFileName=custom.transform`

Ideally it would be nice to add the value for `CustomeTransformFileName` in .csproj file somehow if it always stays the same so build command can just stay
`dotnet publish -c Release`

Did not find an answer to this problem. Is there a way to accomplish this?

**Comment by vijayrkn** [comment]
Any property that is passed to the dotnet publish can be set in the csproj as well. Hope this helps.
